### ISSUE TITLE
'_' prefixed hidden attributes of _annot.json

### ISSUE THREAD

**Issue by raphywink** [IPS-LMU/EMU-webApp#106]
@florianschiel pointed out that we have just had the case that somehow the '_' prefixed hidden attributes of the _annot.json used by the showHierarchy modal (_parent/_x/...) where not removed on showHierarchy modal close action and sent to server and saved. This means that the according _annot.json does not validate on reload i.e. was corrupted. This should definitely be avoided! Should we maybe implement a marshallForPersistence method (that is what we call it in emuR) that recursively removes all _ attributes on showHierarchy modal close as well as on save button click events? Just to make sure the attributes are removed on save as well...

**Comment by MJochim** [comment]
just noting what we decided today: The function already exists, although its name is less fancy than the R one ;-). It's traverseAndClean(object), which resides in the StandardFuncsService.

By design, the data should (already as of now) never get sent to the server without this function being called. But since we (almost certainly) have too little information to find out why it did hapen, in the future we'll also call it on any saving events.

We'll also call the Validationservice before saving. In case the data doesn't validate before saving (which should ofc never happen), the user will not be able to save their work to the server. Not nice but better than saving corrupted data.

@florianschiel: Do you by any chance still have a corrupted copy of the _annot.json in question?

**Comment by raphywink** [comment]
This just happened again! I can send you a copy of a corrupt file or give you the path to an emuDB that has corrupt files in it...

**Comment by MJochim** [comment]
Can we make a copy of the database so the files don't get 'repaired accidentally' ;)? Or is it too large?

**Comment by raphywink** [comment]
As a temp fix I just added this: https://github.com/IPS-LMU/EMU-webApp/commit/1d2679f0fcf02c25882c1be51f05e0ef4c975990 that should fix the Problem shouldn't it?

**Comment by MJochim** [comment]
It is certainly a useful approach!

**Comment by MJochim** [comment]
Good news, I have found a cause for this bug. Hopefully the only one.

**Steps to reproduce**
Use a database with multiple labels on a time level.
Open hierarchy view, close again. Now the directive exists. That includes its watches.
In the labeller, flip from SAMPA to IPA (or whatever label you can choose in your db).
This triggers a watch in the directive (the one at [1]).
The watch render()s the whole bullshit (without the user noticing), thereby creating a bunch of private attributes.
DO NOT open hierarchy view again (this would eventually re-clean).
Save.
Bam.

In fact, I just noticed:

**Steps to reproduce (2)**
Use any database.
Open hierarchy view, close again.
In the labeller, do anything.
This will affect historyService.movesAwayFromLastSave. The directive watches this. Render(). Save. Bam.

**Solution**
I suggest we just keep the traverseAndClean() upon saving in place. I still think it would be advisable to re-validate before saving. You never know.


[1] https://github.com/IPS-LMU/EMU-webApp/blob/ef2c2f65c864c9996ee255038f8cbd182da7f365/app/scripts/directives/emuhierarchy.js#L74
