### ISSUE TITLE
dur off by one problem with TextGrid Files

### ISSUE THREAD

**Issue by raphywink** [IPS-LMU/EMU-webApp#107]
If you drag and drop TextGrid files (`app/testData/oldFormat/msajc003/msajc003.TextGrid` +  `app/testData/oldFormat/msajc003/msajc003.wav`) into the dropzone the duration is off by one Sample!

**Comment by georgraess** [comment]
that is not a problem with the emuwebapp i think...
that is a problem within msajc003.TextGrid 
1) load the new version via drag and drop (msajc003_annot.json) 
2) export it as textgrid
3) remove the "NaN" errors within the exported file (that is a problem which has to be fixed =) )
4) drag an drop the newly generated and cleaned textgrid

-> no problem, no duration off by one

**Comment by raphywink** [comment]
The times in `app/testData/oldFormat/msajc003/msajc003.TextGrid` however seem to be correct! Maybe it is some form of rounding problem while converting times to samples? The times also seem to be fairly truncated after the decimal point.... maybe that has something to do with it?

**Comment by raphywink** [comment]
This is a screenshot from that file incl. the wav file I drag and dropped onto the dropzone:
<img width="404" alt="screen shot 2015-08-09 at 23 00 49" src="https://cloud.githubusercontent.com/assets/435436/9157153/928e4d54-3eea-11e5-8aba-a19e6a482d5c.png">

Something is busted with the calculation of the durations.

**Comment by georgraess** [comment]
yeah exactly ! !please have look at 
app/testData/oldFormat/msajc003/msajc003.TextGrid
and
app/testData/newFormat/ae/0000_ses/msajc003_bndl/msajc003.TextGrid
example: 

Phonetic (IntervalTier) intervals[2] : "V" (in the old format line 408 in the new format line 43)

lower bound of that element
20000*0.187498 = 3749.96 (old value)
20000*0.187525 = 3750.5  (new value)

upper bound of that element
20000*0.256994 = 5139.88 (old value)
20000*0.256975 = 5139.5 (new value)

hence : length of the event
5139.88 - 3749.96 = 1389.92 (old value)
5139.5 - 3750.5 = 1389 (new value)


there is a difference of 0.92 (rounded up to 1 yeah !) in the data

again: the problem is inside the data ......one of both versions is incorrect 
(or maybe was converted incorrectly)! it is not a problem of duration calculation

**Comment by georgraess** [comment]
maybe there is a bug in generating json's 
i'll have a look at this

**Comment by raphywink** [comment]
e48ae09b6617 fixes this
