### ISSUE TITLE
Links not repainted in showHierarchy

### ISSUE THREAD

**Issue by raphywink** [IPS-LMU/EMU-webApp#110]
Don't know if this is the same as #55 but when viewing the hierarchy of a bundle (ae->msajc003) then switching bundle (ae->msajc010) and viewing the next hierarchy not all links are drawn. On collapse an expand they are redrawn correctly.

**Comment by MJochim** [comment]
all I can say for now is that it has nothing to do with #55. it might rather be connected to #106. but i'll really have to dig deeper into this.

**Comment by MJochim** [comment]
I have found the problem but not a solution. After loading a new bundle, but before opening the hierarchy modal, the SVG element is still loaded and 'polluted' with children belonging to the previously loaded bundle. Upon rendering, the directive tries to remove them and at the same time add the children of the new bundle. So, for one operation, it deals with data from multiple bundles. But node IDs are not unique across bundles, so that's where we're running into problems.

We could fix this by destroying the SVG element or the whole modal during bundle loading. Can we do this?

**Comment by MJochim** [comment]
this was fixed one more time in 4c56c4e. that means that e659ad4 (the original ~~fix~~workaround) will probably be reverted.
