### ISSUE TITLE
preview canvas click problem

### ISSUE THREAD

**Issue by raphywink** [IPS-LMU/EMU-webApp#133]
If you are zoomed in somewhat and you click close to the end or start of the wav form the zooming behaviour brakes as it zooms in and does not just move the current viewport position to the edge.

![preview](https://cloud.githubusercontent.com/assets/435436/9522268/3bb9a5da-4cd4-11e5-90d1-c5b0c6798621.png)

**Comment by raphywink** [comment]
The b09c6a3 is a lot better but still not quite right. It should not zoom in any further at the edges when you click there. But this is a minor issue (reopened it anyway so we don't forget)

**Comment by georgraess** [comment]
the problem is the following:
wherever you click on the preview canvas the EMU-webApp assumes that you want to center your 
view on the current mouse position with the current field of view.

for example:
your signal (wav) is 10.000 samples if your current viewPort is 1000 samples wide and you click 100 sample off the right border of the canvas (at position 10.000 - 100 = 9900) 
then the webApp wants to center your view there. that leads to your view being 400 samples beyond the signal (from 9400 to 10400) which of course leads to an error.

so we have to decide... 
A) keeping the "centered" mouse position and we have to zoom in and cut off the rest (which is the current state)
or 
B) we have to move the viewport to the maximum possible sample position (10000 - 1000 = 9000) 
which breaks the mouse "center" behaviour a little bit

**Comment by raphywink** [comment]
I think the default that most people would expect is B) (if I understood you correclty). That would mean if the current viewport ist "XXX to last sample of AudioFile" and someone clicks somewhere in the right half of the current viewport then nothing changes because we can't go further to the right if that makes sense?
