### ISSUE TITLE
changing parallel labels seems to be broken

### ISSUE THREAD

**Issue by raphywink** [IPS-LMU/EMU-webApp#198]
If you open the epgdorsal demo database then flip the phonetic level to a parallel label / attribute definition then you can't change the labels any more. Everything else works but double clicking on the label is broken (no text field opens).

**Comment by georgraess** [comment]
the text field isn't opening because there is no value defined for it in JDR10_bndl.json ( there should be sth like 

   "items": [
     {
      "id": xx,
      "sampleStart": 87710,
      "sampleDur": 929,
      "labels": [
       {
        "name": "Links",
        "value": "O"
       }
      ]
     },

but there is not.

we have multiple options here..... 
- disallow editing when nothing is defined
- error msg to user that nothing is defined
- dynamically create the definition with value = "" and then proceed as normal
i don't know whats best in respect to phonetics.... ?
if we dynamically create the definitions we would have to push that back to the server etc etc....

**Comment by raphywink** [comment]
I looked at this on the weekend as well. I think the best thing to do is to precheck the entire `_annot.json` on load for missing attributeDefinition fields and add empty labels to them if they are missing. Then we can be sure that all the fields are available for the rest of the processing.

**Comment by MJochim** [comment]
A similar problem occours in the hierarchy view. Missing attribute definitions show up as "NO VALUE" there. They can be edited, but not saved. @raphywink's suggestion would help here as well.

**Comment by raphywink** [comment]
I think it is also a "cleaner" way of doing it because then if you save the file back to the emuDB every attrDef. field is set for the entire file. Not just single fields which would be the case if we where to do it dynamically...

**Comment by raphywink** [comment]
Closing this as emuR now creates empty parallel labels when adding new attr. defs. and it hasn't seemed to be an issue since then...
