### ISSUE TITLE
Problems loading app in Firefox and Chrome

### ISSUE THREAD

**Issue by dlukes** [IPS-LMU/EMU-webApp#255]
The current version of EMU-webApp (0.1.12) doesn't load in Firefox at all, and has to be reloaded in Chrome to work properly. Try loading it in a Chrome incognito window; you will have to hit refresh. Looking at the browser console, the first load is apparently needed to set up the Application Cache...?

As for Firefox, if it's not explicitly supported, maybe add that to the README, so that people know? Ideally, the app itself could also detect what client it's running on and display a warning that if things are not working correctly, the user should try switching to Chrome.

**Comment by raphywink** [comment]
I am aware of the reload problem on first visit (due to the app. cache). However, it should work fine in Firefox (what OS are you using?). It is worth noting that Chrome and Firefox treat the application cache differently: 

- Firefox doesn't allow it at all on http (non https) URLs any more (hence no caching)
- Chrome gives a simple deprecated warning

in either case we should update the EMU-webApp to not use the app. cache any more...

**Comment by dlukes** [comment]
> what OS are you using?

macOS and Linux

> Firefox doesn't allow it at all on http (non https) URLs any more (hence no caching)

That's the culprit -- if I load the app via https, Firefox works fine. Trouble is, there are quite a few non-https links to EMU-webApp strewn around the web, e.g. those in the README... But I guess all these issues will be resolved by getting rid of app cache altogether, if you're planning to do that :)

**Comment by raphywink** [comment]
app cache is now on it's way out
